In [ ]:
import numpy as np

In [ ]:
#1create any 3 dimensional array and practice indexing

a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [16]:
 #2 #create array of squares of keys of below dictionary #d (1:2,2:3,3:4,4:5)

 d= {1:2,2:3,3:4,4:5}
 c=np.array(d**2)

TypeError: unsupported operand type(s) for ** or pow(): 'dict' and 'int'

In [28]:
#3 multiply any 2 dim array to identity matrix (2*2) and comment on result

z=np.array([[1,2],[4,5]])
print (z)
i=np.eye(2)
print(i)
print("RESULT=z*i",z*i)

[[1 2]
 [4 5]]
[[1. 0.]
 [0. 1.]]
RESULT=z*i [[1. 0.]
 [0. 5.]]
